# What language the project is of
language: python

# What version(s) of python to test against
python:
  - "2.7"
  - "3.4"
  - "3.5"

services:
  - mysql
  - postgresql

env:
  - DJANGO_VERSION=1.8.12 TRAVIS_DB=sqlite
  - DJANGO_VERSION=1.8.12 TRAVIS_DB=postgres
  - DJANGO_VERSION=1.8.12 TRAVIS_DB=mysql
  - DJANGO_VERSION=1.9.5 TRAVIS_DB=sqlite
  - DJANGO_VERSION=1.9.5 TRAVIS_DB=postgres
  - DJANGO_VERSION=1.9.5 TRAVIS_DB=mysql

# What command to run to install dependencies
install:
  - pip install -r requirements/testing.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q coveralls
  - if [[ $TRAVIS_DB == mysql ]]; then pip install -q mysqlclient; fi
  - if [[ $TRAVIS_DB == postgres ]]; then pip install -q psycopg2; fi
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 4.4.3
  - npm install

# What script to run?
script:
  - coverage run manage.py test
  - npm run unit

# What to do after success?
after_success:
  - coveralls
